
server:
  port: 9001

spring:
  application:
    name: joker-consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8001/eureka/,http://eureka-server2:8002/eureka/,http://eureka-server3:8003/eureka/
  instance:
    instance-id: jokerconsumer-9001  #�Զ������������Ϣ
    prefer-ip-address: true         #����·��������ʾIP��ַ
