
server:
  port: 8005

spring:
  application:
    name: joker-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8001/eureka/,http://eureka-server2:8002/eureka/，http://eureka-server3:8003/eureka/
  instance:
    instance-id: jokerservice-8005  #自定义服务名称信息
    prefer-ip-address: true         #访问路径可以显示IP地址


info:
  app.name: joker-servicecloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$